version: "3.3"
services:
  app:
    build: .    
    ports:
      - "80:80"
    container_name: webapi
    image: webapi:v01
    networks:
      - net
    restart: always

networks:
  net: